console.log('\n================================================================================');
console.log('THE HOG ASSIGNMENT - JOB MATCHING SYSTEM');
console.log('================================================================================\n');
console.log('This project has been refactored to use Event-Driven Architecture with Trigger.dev.');
console.log('\nTo run the system, please use the Trigger.dev CLI:');
console.log('\n  npx trigger.dev@latest dev');
console.log('\nThis will start the local development server and register the following tasks:');
console.log('  - source-jobs (Runs every 2 minutes)');
console.log('  - match-job   (Triggered by source-jobs)');
console.log('  - notify-user (Triggered by match-job)');
console.log('\n================================================================================\n');
